builds:
  - env:
    - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
archives:
  - id: main
    wrap_in_directory: true
    replacements:
      386: i386
      amd64: x86_64
    files:
      - none*
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
