version: 2
jobs:
  release:
    working_directory: /go/src/github.com/tynany/exporter_aggregator
    docker:
      - image: circleci/golang:1.12.4
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
